extends Node

@warning_ignore("unused_signal")
signal TariffSelected(taarif_node:TaarifTabClass)
@warning_ignore("unused_signal")
signal BottomTabSelected(BtnTabNode:BottomTabClass)
@warning_ignore("unused_signal")
signal BottomTabSelectedStr(bottom_tab_node_str:String)
@warning_ignore("unused_signal")
signal HideCurPopup()
@warning_ignore("unused_signal")
signal AppLoaded()
@warning_ignore("unused_signal")
signal ShowPopup(TabName:String,dict: Dictionary)
@warning_ignore("unused_signal")
signal UpdateValues()
@warning_ignore("unused_signal")
signal UpdateHistory()
@warning_ignore("unused_signal")
signal UpdateHebrewMonth()
@warning_ignore("unused_signal")
signal AdjustBottomBar(banner_height:int)
